#include <iostream>

void Log(const char* message);
void IntegerBasics();
void StringBasics();
void StringOperations1();
void OtherTypes();
void Cons1();
void Cons2();
void ConstCaller();
void MutableLambdas1();
void MIL();
void CreatingOnStack();
void CreatingOnHeap();
void NewKey();
void ObjectLifetime();
void ScopedPtr();
void SmartPtr();
void CopyConst();
void ArrowBasics();
void DynamicArray();

int main() {
	Log("Hello World!");
	std::cout << "----------------------------------------" << std::endl;
	std::cout << "\n\n\nIntegerBasics\n" << std::endl;
	IntegerBasics();
	std::cout << "----------------------------------------" << std::endl;
	std::cout << "\n\n\nStringBasics\n" << std::endl;
	StringBasics();
	std::cout << "----------------------------------------" << std::endl;
	std::cout << "\n\n\nStringOperations1\n" << std::endl;
	StringOperations1();
	std::cout << "----------------------------------------" << std::endl;
	std::cout << "\n\n\nOther Types\n" << std::endl;
	OtherTypes();
	std::cout << "----------------------------------------" << std::endl;
	std::cout << "\n\n\nConstants 1\n" << std::endl;
	Cons1();
	std::cout << "----------------------------------------" << std::endl;
	std::cout << "\n\n\nConstants 2 \n" << std::endl;
	Cons2();
	std::cout << "----------------------------------------" << std::endl;
	std::cout << "\n\n\nConstants 3 \n" << std::endl;
	ConstCaller();
	std::cout << "----------------------------------------" << std::endl;
	std::cout << "\n" << std::endl;
	MutableLambdas1();
	std::cout << "----------------------------------------" << std::endl;
	std::cout << "\n\n\nMember Initializer List \n" << std::endl;
	MIL();
	std::cout << "----------------------------------------" << std::endl;
	std::cout << "\n\n\nVar on Stack \n" << std::endl;
	CreatingOnStack();
	std::cout << "----------------------------------------" << std::endl;
	std::cout << "\n\n\nVar on Heap \n" << std::endl;
	CreatingOnHeap();
	std::cout << "----------------------------------------" << std::endl;
	std::cout << "\n\n\nnew Keyword \n" << std::endl;
	NewKey();
	std::cout << "----------------------------------------" << std::endl;
	std::cout << "\n\n\nObject Lifetime \n" << std::endl;
	ObjectLifetime();
	std::cout << "----------------------------------------" << std::endl;
	std::cout << "\n\n\nScoped Pointer \n" << std::endl;
	ScopedPtr();
	std::cout << "----------------------------------------" << std::endl;
	std::cout << "\n\n\nSmart Pointer \n" << std::endl;
	SmartPtr();
	std::cout << "----------------------------------------" << std::endl;
	std::cout << "\n\n\nCopying and Copy Constructs \n" << std::endl;
	CopyConst();
	std::cout << "----------------------------------------" << std::endl;
	std::cout << "\n\n\nArrow Basics \n" << std::endl;
	ArrowBasics();
	std::cout << "----------------------------------------" << std::endl;
	std::cout << "\n\n\nDynamic Arrays \n" << std::endl;
	DynamicArray();
	std::cout << "----------------------------------------" << std::endl;
	std::cin.get();
};